### ISSUE TITLE
Issues with customizing report through gene panel name

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/chanjo2#296]
In the gene panel customize:

<img width="842" alt="chanjo2_customize" src="https://github.com/Clinical-Genomics/chanjo2/assets/7374399/b6911e19-1930-4538-b9fb-84c14521bad2">

The panel can be updated using a gene panel name. This was something our geneticists instinctively immediately tried.

I am unsure whether it works as intended though. Updating the name triggers a page load, but:

- The gene panel name disappeared (in my case at least)
- Only one gene was shown (same as before the update) despite the panel having 28 genes

I used both the "Full name" and the "Panel ID" of the panel when trying this out.

**Comment by northwestwitch** [comment]
Ah yes, there is a bug, in the sense that the form should allow you to update the name of the panel shown on the report , and this is not working at the moment (I'll fix).

What is not expected is that if you pick the name of another existing panel in scout it will show the coverage stats on that other panel. This is because chanjo2 is disconnected from scout and it has no access to its panels/genes. Once you are on the report page you can only update genes used in the stats by modifying the gene list in that form.

**Comment by Jakob37** [comment]
> Ah yes, there is a bug, in the sense that the form should allow you to update the name of the panel shown on the report , and this is not working at the moment (I'll fix).
> 
> What is not expected is that if you pick the name of another existing panel in scout it will show the coverage stats on that other panel. This is because chanjo2 is disconnected from scout and has no access to its panels/genes. Once you are on the report page you can only update genes used in the stats by modifying the gene list in that form.

Aha, I see! Yes, now when reading more carefully it makes sense "Gene panel name to display", not "Gene panel to display" 🙈 Thank you for clarifying!
